"""categorias, localizacoes e regras de visibilidade

Revision ID: 1a1e14808dd4
Revises: a2d5ca4f8b81
Create Date: 2026-06-28 06:23:33.071631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # usado por colunas JSONB(astext_type=Text())
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1a1e14808dd4'
down_revision = 'a2d5ca4f8b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id', 'nome', name='uq_categoria_org_nome')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_organizacao_id'), ['organizacao_id'], unique=False)

    op.create_table('localizacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setor_id', 'nome', name='uq_localizacao_setor_nome')
    )
    with op.batch_alter_table('localizacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_localizacoes_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_localizacoes_setor_id'), ['setor_id'], unique=False)

    op.create_table('regras_visibilidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setor_observador_id', sa.Integer(), nullable=False),
    sa.Column('setor_alvo_id', sa.Integer(), nullable=False),
    sa.Column('inclui_subarvore', sa.Boolean(), nullable=False),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setor_alvo_id'], ['setores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setor_observador_id'], ['setores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setor_observador_id', 'setor_alvo_id', name='uq_visibilidade_par')
    )
    with op.batch_alter_table('regras_visibilidade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regras_visibilidade_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_regras_visibilidade_setor_alvo_id'), ['setor_alvo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_regras_visibilidade_setor_observador_id'), ['setor_observador_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regras_visibilidade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regras_visibilidade_setor_observador_id'))
        batch_op.drop_index(batch_op.f('ix_regras_visibilidade_setor_alvo_id'))
        batch_op.drop_index(batch_op.f('ix_regras_visibilidade_organizacao_id'))

    op.drop_table('regras_visibilidade')
    with op.batch_alter_table('localizacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_localizacoes_setor_id'))
        batch_op.drop_index(batch_op.f('ix_localizacoes_organizacao_id'))

    op.drop_table('localizacoes')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_organizacao_id'))

    op.drop_table('categorias')
    # ### end Alembic commands ###
