"""Fase 6: emprestimos (consumivel e duravel)

Revision ID: 27bf46b91fcf
Revises: e0a2fb075c41
Create Date: 2026-06-28 16:54:08.947275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # usado por colunas JSONB(astext_type=Text())
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '27bf46b91fcf'
down_revision = 'e0a2fb075c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emprestimos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('ativo_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantidade_devolvida', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('destinatario', sa.String(length=160), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('data_emprestimo', sa.Date(), nullable=True),
    sa.Column('data_prevista', sa.Date(), nullable=True),
    sa.Column('data_devolucao', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emprestimos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emprestimos_ativo_id'), ['ativo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emprestimos_data_prevista'), ['data_prevista'], unique=False)
        batch_op.create_index(batch_op.f('ix_emprestimos_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emprestimos_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emprestimos_setor_id'), ['setor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emprestimos_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprestimos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emprestimos_status'))
        batch_op.drop_index(batch_op.f('ix_emprestimos_setor_id'))
        batch_op.drop_index(batch_op.f('ix_emprestimos_produto_id'))
        batch_op.drop_index(batch_op.f('ix_emprestimos_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_emprestimos_data_prevista'))
        batch_op.drop_index(batch_op.f('ix_emprestimos_ativo_id'))

    op.drop_table('emprestimos')
    # ### end Alembic commands ###
