"""ativos (patrimonio)

Revision ID: 315ecfa59639
Revises: 8d5134c79453
Create Date: 2026-06-28 10:48:42.813033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # usado por colunas JSONB(astext_type=Text())
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '315ecfa59639'
down_revision = '8d5134c79453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('tombamento', sa.String(length=60), nullable=True),
    sa.Column('numero_serie', sa.String(length=80), nullable=True),
    sa.Column('marca', sa.String(length=80), nullable=True),
    sa.Column('modelo', sa.String(length=80), nullable=True),
    sa.Column('fornecedor', sa.String(length=160), nullable=True),
    sa.Column('data_aquisicao', sa.Date(), nullable=True),
    sa.Column('valor_aquisicao', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('garantia_ate', sa.Date(), nullable=True),
    sa.Column('vida_util_meses', sa.Integer(), nullable=True),
    sa.Column('valor_residual', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estado_conservacao', sa.String(length=12), nullable=False),
    sa.Column('status_ciclo', sa.String(length=14), nullable=False),
    sa.Column('setor_atual_id', sa.Integer(), nullable=True),
    sa.Column('usuario_responsavel_id', sa.Integer(), nullable=True),
    sa.Column('ultima_revisao_em', sa.Date(), nullable=True),
    sa.Column('proxima_revisao_em', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('campos', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['setor_atual_id'], ['setores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_responsavel_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id', 'numero_serie', name='uq_ativo_org_serie'),
    sa.UniqueConstraint('organizacao_id', 'tombamento', name='uq_ativo_org_tombamento')
    )
    with op.batch_alter_table('ativos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ativos_ativo'), ['ativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_ativos_numero_serie'), ['numero_serie'], unique=False)
        batch_op.create_index(batch_op.f('ix_ativos_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ativos_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ativos_proxima_revisao_em'), ['proxima_revisao_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_ativos_setor_atual_id'), ['setor_atual_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ativos_status_ciclo'), ['status_ciclo'], unique=False)
        batch_op.create_index(batch_op.f('ix_ativos_tombamento'), ['tombamento'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ativos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ativos_tombamento'))
        batch_op.drop_index(batch_op.f('ix_ativos_status_ciclo'))
        batch_op.drop_index(batch_op.f('ix_ativos_setor_atual_id'))
        batch_op.drop_index(batch_op.f('ix_ativos_proxima_revisao_em'))
        batch_op.drop_index(batch_op.f('ix_ativos_produto_id'))
        batch_op.drop_index(batch_op.f('ix_ativos_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_ativos_numero_serie'))
        batch_op.drop_index(batch_op.f('ix_ativos_ativo'))

    op.drop_table('ativos')
    # ### end Alembic commands ###
