"""transferencias e itens

Revision ID: 8d5134c79453
Revises: 9ea7c5796112
Create Date: 2026-06-28 10:31:53.641312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # usado por colunas JSONB(astext_type=Text())
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '8d5134c79453'
down_revision = '9ea7c5796112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transferencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('setor_origem_id', sa.Integer(), nullable=False),
    sa.Column('setor_destino_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=28), nullable=False),
    sa.Column('enviado_por', sa.Integer(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recebido_por', sa.Integer(), nullable=True),
    sa.Column('recebido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('corrigido_por', sa.Integer(), nullable=True),
    sa.Column('corrigido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacoes_envio', sa.Text(), nullable=True),
    sa.Column('observacoes_recebimento', sa.Text(), nullable=True),
    sa.Column('observacoes_correcao', sa.Text(), nullable=True),
    sa.Column('documento_envio_id', sa.Integer(), nullable=True),
    sa.Column('documento_recebimento_id', sa.Integer(), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['corrigido_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enviado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recebido_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['setor_destino_id'], ['setores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setor_origem_id'], ['setores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transferencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transferencias_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transferencias_setor_destino_id'), ['setor_destino_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transferencias_setor_origem_id'), ['setor_origem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transferencias_status'), ['status'], unique=False)

    op.create_table('transferencia_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transferencia_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('ativo_id', sa.Integer(), nullable=True),
    sa.Column('quantidade_enviada', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantidade_recebida', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('quantidade_corrigida', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('divergencia', sa.Boolean(), nullable=False),
    sa.Column('motivo_divergencia', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transferencia_id'], ['transferencias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transferencia_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transferencia_itens_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transferencia_itens_transferencia_id'), ['transferencia_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferencia_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transferencia_itens_transferencia_id'))
        batch_op.drop_index(batch_op.f('ix_transferencia_itens_produto_id'))

    op.drop_table('transferencia_itens')
    with op.batch_alter_table('transferencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transferencias_status'))
        batch_op.drop_index(batch_op.f('ix_transferencias_setor_origem_id'))
        batch_op.drop_index(batch_op.f('ix_transferencias_setor_destino_id'))
        batch_op.drop_index(batch_op.f('ix_transferencias_organizacao_id'))

    op.drop_table('transferencias')
    # ### end Alembic commands ###
