"""produtos e definicoes de campo

Revision ID: 90d4ef55b40f
Revises: 1a1e14808dd4
Create Date: 2026-06-28 09:14:03.014602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # usado por colunas JSONB(astext_type=Text())
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90d4ef55b40f'
down_revision = '1a1e14808dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('definicoes_campo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidade', sa.String(length=20), nullable=False),
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('rotulo', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('opcoes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ajuda', sa.String(length=255), nullable=True),
    sa.Column('aplica_a_categoria_id', sa.Integer(), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['aplica_a_categoria_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id', 'entidade', 'chave', name='uq_def_campo_org_ent_chave')
    )
    with op.batch_alter_table('definicoes_campo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_definicoes_campo_aplica_a_categoria_id'), ['aplica_a_categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_definicoes_campo_entidade'), ['entidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_definicoes_campo_organizacao_id'), ['organizacao_id'], unique=False)

    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('tipo_controle', sa.String(length=12), nullable=False),
    sa.Column('unidade', sa.String(length=12), nullable=False),
    sa.Column('estoque_minimo', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('estoque_maximo', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('marca', sa.String(length=80), nullable=True),
    sa.Column('modelo', sa.String(length=80), nullable=True),
    sa.Column('valor_unitario_referencia', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('custo_medio', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('campos', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id', 'sku', name='uq_produto_org_sku')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_ativo'), ['ativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_sku'), ['sku'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_sku'))
        batch_op.drop_index(batch_op.f('ix_produtos_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_produtos_nome'))
        batch_op.drop_index(batch_op.f('ix_produtos_categoria_id'))
        batch_op.drop_index(batch_op.f('ix_produtos_ativo'))

    op.drop_table('produtos')
    with op.batch_alter_table('definicoes_campo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_definicoes_campo_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_definicoes_campo_entidade'))
        batch_op.drop_index(batch_op.f('ix_definicoes_campo_aplica_a_categoria_id'))

    op.drop_table('definicoes_campo')
    # ### end Alembic commands ###
