"""Fase 7: documentos e modelos de documento

Revision ID: 92f56ade10c7
Revises: 27bf46b91fcf
Create Date: 2026-06-28 17:08:35.265767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # usado por colunas JSONB(astext_type=Text())
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92f56ade10c7'
down_revision = '27bf46b91fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelos_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=24), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('conteudo_html', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id', 'tipo', name='uq_modelo_org_tipo')
    )
    with op.batch_alter_table('modelos_documento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modelos_documento_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_modelos_documento_tipo'), ['tipo'], unique=False)

    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=24), nullable=False),
    sa.Column('sequencial', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('setor_origem_id', sa.Integer(), nullable=True),
    sa.Column('setor_destino_id', sa.Integer(), nullable=True),
    sa.Column('modelo_id', sa.Integer(), nullable=True),
    sa.Column('emitido_por_id', sa.Integer(), nullable=True),
    sa.Column('arquivo', sa.String(length=255), nullable=True),
    sa.Column('formato', sa.String(length=8), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('assinado_por', sa.String(length=160), nullable=True),
    sa.Column('dados', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['emitido_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_documento.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setor_destino_id'], ['setores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['setor_origem_id'], ['setores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id', 'tipo', 'ano', 'sequencial', name='uq_documento_numero')
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_ano'), ['ano'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_setor_destino_id'), ['setor_destino_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_setor_origem_id'), ['setor_origem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_tipo'), ['tipo'], unique=False)

    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documento_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_movimentacoes_documento_id'), ['documento_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_movimentacoes_documento_id', 'documentos', ['documento_id'], ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_movimentacoes_documento_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_movimentacoes_documento_id'))
        batch_op.drop_column('documento_id')

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_tipo'))
        batch_op.drop_index(batch_op.f('ix_documentos_setor_origem_id'))
        batch_op.drop_index(batch_op.f('ix_documentos_setor_destino_id'))
        batch_op.drop_index(batch_op.f('ix_documentos_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_documentos_numero'))
        batch_op.drop_index(batch_op.f('ix_documentos_ano'))

    op.drop_table('documentos')
    with op.batch_alter_table('modelos_documento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modelos_documento_tipo'))
        batch_op.drop_index(batch_op.f('ix_modelos_documento_organizacao_id'))

    op.drop_table('modelos_documento')
    # ### end Alembic commands ###
