"""saldos de estoque e movimentacoes

Revision ID: 9ea7c5796112
Revises: 90d4ef55b40f
Create Date: 2026-06-28 10:19:39.306237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # usado por colunas JSONB(astext_type=Text())
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '9ea7c5796112'
down_revision = '90d4ef55b40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes_movimentacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lotes_movimentacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lotes_movimentacao_organizacao_id'), ['organizacao_id'], unique=False)

    op.create_table('movimentacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('ativo_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('origem_setor_id', sa.Integer(), nullable=True),
    sa.Column('destino_setor_id', sa.Integer(), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('destinatario', sa.String(length=160), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['destino_setor_id'], ['setores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_movimentacao.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origem_setor_id'], ['setores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentacoes_ativo_id'), ['ativo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_destino_setor_id'), ['destino_setor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_lote_id'), ['lote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_origem_setor_id'), ['origem_setor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_tipo'), ['tipo'], unique=False)

    op.create_table('saldos_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantidade_em_transito', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'setor_id', name='uq_saldo_produto_setor')
    )
    with op.batch_alter_table('saldos_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saldos_estoque_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saldos_estoque_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saldos_estoque_setor_id'), ['setor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saldos_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saldos_estoque_setor_id'))
        batch_op.drop_index(batch_op.f('ix_saldos_estoque_produto_id'))
        batch_op.drop_index(batch_op.f('ix_saldos_estoque_organizacao_id'))

    op.drop_table('saldos_estoque')
    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentacoes_tipo'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_produto_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_origem_setor_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_lote_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_destino_setor_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_ativo_id'))

    op.drop_table('movimentacoes')
    with op.batch_alter_table('lotes_movimentacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lotes_movimentacao_organizacao_id'))

    op.drop_table('lotes_movimentacao')
    # ### end Alembic commands ###
