"""Fase 8: inventario e itens

Revision ID: a1b83bdda501
Revises: 92f56ade10c7
Create Date: 2026-06-28 17:21:48.326115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # usado por colunas JSONB(astext_type=Text())
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a1b83bdda501'
down_revision = '92f56ade10c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fechamento', sa.Date(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventarios_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventarios_setor_id'), ['setor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventarios_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventarios_tipo'), ['tipo'], unique=False)

    op.create_table('inventario_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('ativo_id', sa.Integer(), nullable=True),
    sa.Column('quantidade_esperada', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantidade_contada', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('estado_conservacao', sa.String(length=12), nullable=True),
    sa.Column('status_ciclo', sa.String(length=14), nullable=True),
    sa.Column('contado', sa.Boolean(), nullable=False),
    sa.Column('divergencia', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventario_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventario_itens_ativo_id'), ['ativo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventario_itens_inventario_id'), ['inventario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventario_itens_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventario_itens_produto_id'), ['produto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventario_itens_produto_id'))
        batch_op.drop_index(batch_op.f('ix_inventario_itens_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_inventario_itens_inventario_id'))
        batch_op.drop_index(batch_op.f('ix_inventario_itens_ativo_id'))

    op.drop_table('inventario_itens')
    with op.batch_alter_table('inventarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventarios_tipo'))
        batch_op.drop_index(batch_op.f('ix_inventarios_status'))
        batch_op.drop_index(batch_op.f('ix_inventarios_setor_id'))
        batch_op.drop_index(batch_op.f('ix_inventarios_organizacao_id'))

    op.drop_table('inventarios')
    # ### end Alembic commands ###
