"""estrutura inicial: organizacoes, usuarios, rbac, setores, auditoria

Revision ID: a2d5ca4f8b81
Revises: 
Create Date: 2026-06-28 05:54:51.302300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2d5ca4f8b81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizacao_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=80), nullable=False),
    sa.Column('entidade', sa.String(length=60), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('dados_antes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('dados_depois', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('organizacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('plano', sa.String(length=40), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('cor_primaria', sa.String(length=9), nullable=False),
    sa.Column('cor_secundaria', sa.String(length=9), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizacoes_slug'), ['slug'], unique=True)

    op.create_table('permissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissoes_chave'), ['chave'], unique=True)

    op.create_table('papeis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('sistema', sa.Boolean(), nullable=False),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id', 'nome', name='uq_papel_org_nome')
    )
    with op.batch_alter_table('papeis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_papeis_organizacao_id'), ['organizacao_id'], unique=False)

    op.create_table('setores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=True),
    sa.Column('setor_pai_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('permite_visualizacao_externa', sa.Boolean(), nullable=False),
    sa.Column('poder_compra', sa.Boolean(), nullable=False),
    sa.Column('centro_custo', sa.String(length=40), nullable=True),
    sa.Column('orcamento_anual', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setor_pai_id'], ['setores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id', 'codigo', name='uq_setor_org_codigo')
    )
    with op.batch_alter_table('setores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setores_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_setores_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_setores_setor_pai_id'), ['setor_pai_id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=80), nullable=True),
    sa.Column('matricula', sa.String(length=40), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('superadmin', sa.Boolean(), nullable=False),
    sa.Column('deve_trocar_senha', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id', 'email', name='uq_usuario_org_email'),
    sa.UniqueConstraint('organizacao_id', 'username', name='uq_usuario_org_username')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=False)

    op.create_table('papel_permissao',
    sa.Column('papel_id', sa.Integer(), nullable=False),
    sa.Column('permissao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['papel_id'], ['papeis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('papel_id', 'permissao_id')
    )
    op.create_table('usuario_papel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('papel_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['papel_id'], ['papeis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'papel_id', 'setor_id', name='uq_usuario_papel_setor')
    )
    with op.batch_alter_table('usuario_papel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_papel_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_papel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_papel_usuario_id'))

    op.drop_table('usuario_papel')
    op.drop_table('papel_permissao')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.drop_index(batch_op.f('ix_usuarios_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('setores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setores_setor_pai_id'))
        batch_op.drop_index(batch_op.f('ix_setores_path'))
        batch_op.drop_index(batch_op.f('ix_setores_organizacao_id'))

    op.drop_table('setores')
    with op.batch_alter_table('papeis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papeis_organizacao_id'))

    op.drop_table('papeis')
    with op.batch_alter_table('permissoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissoes_chave'))

    op.drop_table('permissoes')
    with op.batch_alter_table('organizacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizacoes_slug'))

    op.drop_table('organizacoes')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_acao'))

    op.drop_table('auditoria')
    # ### end Alembic commands ###
