"""compras: fornecedores, pedidos e notas fiscais

Revision ID: ca5f8cdf62cd
Revises: 315ecfa59639
Create Date: 2026-06-28 11:33:05.667448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # usado por colunas JSONB(astext_type=Text())
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca5f8cdf62cd'
down_revision = '315ecfa59639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('tipo_pessoa', sa.String(length=2), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('inscricao_estadual', sa.String(length=30), nullable=True),
    sa.Column('contato', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('telefone', sa.String(length=40), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('campos', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id', 'documento', name='uq_fornecedor_org_documento')
    )
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fornecedores_ativo'), ['ativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_fornecedores_documento'), ['documento'], unique=False)
        batch_op.create_index(batch_op.f('ix_fornecedores_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_fornecedores_organizacao_id'), ['organizacao_id'], unique=False)

    op.create_table('pedidos_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('exercicio', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('valor_estimado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=True),
    sa.Column('aprovador_id', sa.Integer(), nullable=True),
    sa.Column('data_aprovacao', sa.Date(), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['aprovador_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id', 'numero', name='uq_pedido_org_numero')
    )
    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_compra_exercicio'), ['exercicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_compra_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_compra_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_compra_setor_id'), ['setor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_compra_status'), ['status'], unique=False)

    op.create_table('notas_fiscais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=True),
    sa.Column('chave_nfe', sa.String(length=44), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('arquivo_pdf', sa.String(length=255), nullable=True),
    sa.Column('arquivo_xml', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_compra.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id', 'fornecedor_id', 'numero', 'serie', name='uq_nf_org_forn_num_serie')
    )
    with op.batch_alter_table('notas_fiscais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_fiscais_chave_nfe'), ['chave_nfe'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_fiscais_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_fiscais_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_fiscais_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_fiscais_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_fiscais_setor_id'), ['setor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_fiscais_status'), ['status'], unique=False)

    op.create_table('pedido_compra_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_compra.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedido_compra_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_compra_itens_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_compra_itens_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_compra_itens_produto_id'), ['produto_id'], unique=False)

    op.create_table('nota_fiscal_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['nota_id'], ['notas_fiscais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nota_fiscal_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nota_fiscal_itens_nota_id'), ['nota_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nota_fiscal_itens_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nota_fiscal_itens_produto_id'), ['produto_id'], unique=False)

    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_fiscal_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_movimentacoes_nota_fiscal_id'), ['nota_fiscal_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_movimentacoes_nota_fiscal_id', 'notas_fiscais',
            ['nota_fiscal_id'], ['id'], ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_movimentacoes_nota_fiscal_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_movimentacoes_nota_fiscal_id'))
        batch_op.drop_column('nota_fiscal_id')

    with op.batch_alter_table('nota_fiscal_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nota_fiscal_itens_produto_id'))
        batch_op.drop_index(batch_op.f('ix_nota_fiscal_itens_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_nota_fiscal_itens_nota_id'))

    op.drop_table('nota_fiscal_itens')
    with op.batch_alter_table('pedido_compra_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_compra_itens_produto_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_compra_itens_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_compra_itens_organizacao_id'))

    op.drop_table('pedido_compra_itens')
    with op.batch_alter_table('notas_fiscais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_fiscais_status'))
        batch_op.drop_index(batch_op.f('ix_notas_fiscais_setor_id'))
        batch_op.drop_index(batch_op.f('ix_notas_fiscais_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_notas_fiscais_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_notas_fiscais_numero'))
        batch_op.drop_index(batch_op.f('ix_notas_fiscais_fornecedor_id'))
        batch_op.drop_index(batch_op.f('ix_notas_fiscais_chave_nfe'))

    op.drop_table('notas_fiscais')
    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_compra_status'))
        batch_op.drop_index(batch_op.f('ix_pedidos_compra_setor_id'))
        batch_op.drop_index(batch_op.f('ix_pedidos_compra_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_pedidos_compra_fornecedor_id'))
        batch_op.drop_index(batch_op.f('ix_pedidos_compra_exercicio'))

    op.drop_table('pedidos_compra')
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fornecedores_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_fornecedores_nome'))
        batch_op.drop_index(batch_op.f('ix_fornecedores_documento'))
        batch_op.drop_index(batch_op.f('ix_fornecedores_ativo'))

    op.drop_table('fornecedores')
    # ### end Alembic commands ###
