"""Fase 5c: compras publicas (licitacao, ata, contrato, empenho, despesa)

Revision ID: e0a2fb075c41
Revises: ca5f8cdf62cd
Create Date: 2026-06-28 15:43:42.057531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # usado por colunas JSONB(astext_type=Text())
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e0a2fb075c41'
down_revision = 'ca5f8cdf62cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dotacoes_orcamentarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercicio', sa.Integer(), nullable=False),
    sa.Column('programa_trabalho', sa.String(length=60), nullable=True),
    sa.Column('natureza_despesa', sa.String(length=40), nullable=True),
    sa.Column('fonte_recurso', sa.String(length=40), nullable=True),
    sa.Column('unidade_orcamentaria', sa.String(length=80), nullable=True),
    sa.Column('descricao', sa.String(length=160), nullable=True),
    sa.Column('valor_dotado', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('valor_empenhado', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dotacoes_orcamentarias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dotacoes_orcamentarias_exercicio'), ['exercicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_dotacoes_orcamentarias_organizacao_id'), ['organizacao_id'], unique=False)

    op.create_table('processos_contratacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_processo', sa.String(length=40), nullable=False),
    sa.Column('objeto', sa.Text(), nullable=False),
    sa.Column('modalidade', sa.String(length=20), nullable=False),
    sa.Column('procedimento_auxiliar', sa.String(length=20), nullable=False),
    sa.Column('valor_estimado', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('data_abertura', sa.Date(), nullable=True),
    sa.Column('data_homologacao', sa.Date(), nullable=True),
    sa.Column('numero_pncp', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id', 'numero_processo', name='uq_processo_org_numero')
    )
    with op.batch_alter_table('processos_contratacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processos_contratacao_modalidade'), ['modalidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_contratacao_numero_processo'), ['numero_processo'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_contratacao_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_contratacao_setor_id'), ['setor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_contratacao_status'), ['status'], unique=False)

    op.create_table('atas_registro_precos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('vigencia_inicio', sa.Date(), nullable=True),
    sa.Column('vigencia_fim', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processo_id'], ['processos_contratacao.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id', 'numero', name='uq_ata_org_numero')
    )
    with op.batch_alter_table('atas_registro_precos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atas_registro_precos_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_atas_registro_precos_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_atas_registro_precos_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_atas_registro_precos_processo_id'), ['processo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_atas_registro_precos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_atas_registro_precos_vigencia_fim'), ['vigencia_fim'], unique=False)

    op.create_table('ata_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ata_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('quantidade_registrada', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('preco_registrado', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('saldo_quantidade', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ata_id'], ['atas_registro_precos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ata_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ata_itens_ata_id'), ['ata_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ata_itens_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ata_itens_produto_id'), ['produto_id'], unique=False)

    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('objeto', sa.Text(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=True),
    sa.Column('ata_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('valor_global', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('vigencia_inicio', sa.Date(), nullable=True),
    sa.Column('vigencia_fim', sa.Date(), nullable=True),
    sa.Column('fiscal_id', sa.Integer(), nullable=True),
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.Column('garantia', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ata_id'], ['atas_registro_precos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fiscal_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gestor_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processo_id'], ['processos_contratacao.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id', 'numero', name='uq_contrato_org_numero')
    )
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contratos_ata_id'), ['ata_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_processo_id'), ['processo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_vigencia_fim'), ['vigencia_fim'], unique=False)

    op.create_table('contrato_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('saldo_quantidade', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('saldo_valor', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contrato_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contrato_itens_contrato_id'), ['contrato_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contrato_itens_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contrato_itens_produto_id'), ['produto_id'], unique=False)

    op.create_table('empenhos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('saldo_a_liquidar', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('dotacao_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('ata_id', sa.Integer(), nullable=True),
    sa.Column('processo_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ata_id'], ['atas_registro_precos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dotacao_id'], ['dotacoes_orcamentarias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processo_id'], ['processos_contratacao.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id', 'numero', name='uq_empenho_org_numero')
    )
    with op.batch_alter_table('empenhos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empenhos_ata_id'), ['ata_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_empenhos_contrato_id'), ['contrato_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_empenhos_dotacao_id'), ['dotacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_empenhos_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_empenhos_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_empenhos_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_empenhos_processo_id'), ['processo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_empenhos_status'), ['status'], unique=False)

    op.create_table('termos_aditivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=True),
    sa.Column('tipo', sa.String(length=16), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('nova_vigencia', sa.Date(), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('termos_aditivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_termos_aditivos_contrato_id'), ['contrato_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_termos_aditivos_organizacao_id'), ['organizacao_id'], unique=False)

    op.create_table('recebimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('nota_fiscal_id', sa.Integer(), nullable=True),
    sa.Column('empenho_id', sa.Integer(), nullable=True),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('conforme', sa.Boolean(), nullable=False),
    sa.Column('recebido_por_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empenho_id'], ['empenhos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nota_fiscal_id'], ['notas_fiscais.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recebido_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recebimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recebimentos_contrato_id'), ['contrato_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recebimentos_empenho_id'), ['empenho_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recebimentos_nota_fiscal_id'), ['nota_fiscal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recebimentos_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recebimentos_setor_id'), ['setor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recebimentos_tipo'), ['tipo'], unique=False)

    op.create_table('liquidacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empenho_id', sa.Integer(), nullable=False),
    sa.Column('nota_fiscal_id', sa.Integer(), nullable=True),
    sa.Column('recebimento_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('atestado_por_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['atestado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empenho_id'], ['empenhos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nota_fiscal_id'], ['notas_fiscais.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recebimento_id'], ['recebimentos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liquidacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liquidacoes_empenho_id'), ['empenho_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquidacoes_nota_fiscal_id'), ['nota_fiscal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquidacoes_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquidacoes_recebimento_id'), ['recebimento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquidacoes_status'), ['status'], unique=False)

    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liquidacao_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('ordem_bancaria', sa.String(length=60), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('organizacao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['liquidacao_id'], ['liquidacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagamentos_liquidacao_id'), ['liquidacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagamentos_organizacao_id'), ['organizacao_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamentos_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_pagamentos_liquidacao_id'))

    op.drop_table('pagamentos')
    with op.batch_alter_table('liquidacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liquidacoes_status'))
        batch_op.drop_index(batch_op.f('ix_liquidacoes_recebimento_id'))
        batch_op.drop_index(batch_op.f('ix_liquidacoes_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_liquidacoes_nota_fiscal_id'))
        batch_op.drop_index(batch_op.f('ix_liquidacoes_empenho_id'))

    op.drop_table('liquidacoes')
    with op.batch_alter_table('recebimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recebimentos_tipo'))
        batch_op.drop_index(batch_op.f('ix_recebimentos_setor_id'))
        batch_op.drop_index(batch_op.f('ix_recebimentos_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_recebimentos_nota_fiscal_id'))
        batch_op.drop_index(batch_op.f('ix_recebimentos_empenho_id'))
        batch_op.drop_index(batch_op.f('ix_recebimentos_contrato_id'))

    op.drop_table('recebimentos')
    with op.batch_alter_table('termos_aditivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_termos_aditivos_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_termos_aditivos_contrato_id'))

    op.drop_table('termos_aditivos')
    with op.batch_alter_table('empenhos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empenhos_status'))
        batch_op.drop_index(batch_op.f('ix_empenhos_processo_id'))
        batch_op.drop_index(batch_op.f('ix_empenhos_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_empenhos_numero'))
        batch_op.drop_index(batch_op.f('ix_empenhos_fornecedor_id'))
        batch_op.drop_index(batch_op.f('ix_empenhos_dotacao_id'))
        batch_op.drop_index(batch_op.f('ix_empenhos_contrato_id'))
        batch_op.drop_index(batch_op.f('ix_empenhos_ata_id'))

    op.drop_table('empenhos')
    with op.batch_alter_table('contrato_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contrato_itens_produto_id'))
        batch_op.drop_index(batch_op.f('ix_contrato_itens_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_contrato_itens_contrato_id'))

    op.drop_table('contrato_itens')
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contratos_vigencia_fim'))
        batch_op.drop_index(batch_op.f('ix_contratos_status'))
        batch_op.drop_index(batch_op.f('ix_contratos_processo_id'))
        batch_op.drop_index(batch_op.f('ix_contratos_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_contratos_numero'))
        batch_op.drop_index(batch_op.f('ix_contratos_fornecedor_id'))
        batch_op.drop_index(batch_op.f('ix_contratos_ata_id'))

    op.drop_table('contratos')
    with op.batch_alter_table('ata_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ata_itens_produto_id'))
        batch_op.drop_index(batch_op.f('ix_ata_itens_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_ata_itens_ata_id'))

    op.drop_table('ata_itens')
    with op.batch_alter_table('atas_registro_precos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atas_registro_precos_vigencia_fim'))
        batch_op.drop_index(batch_op.f('ix_atas_registro_precos_status'))
        batch_op.drop_index(batch_op.f('ix_atas_registro_precos_processo_id'))
        batch_op.drop_index(batch_op.f('ix_atas_registro_precos_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_atas_registro_precos_numero'))
        batch_op.drop_index(batch_op.f('ix_atas_registro_precos_fornecedor_id'))

    op.drop_table('atas_registro_precos')
    with op.batch_alter_table('processos_contratacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processos_contratacao_status'))
        batch_op.drop_index(batch_op.f('ix_processos_contratacao_setor_id'))
        batch_op.drop_index(batch_op.f('ix_processos_contratacao_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_processos_contratacao_numero_processo'))
        batch_op.drop_index(batch_op.f('ix_processos_contratacao_modalidade'))

    op.drop_table('processos_contratacao')
    with op.batch_alter_table('dotacoes_orcamentarias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dotacoes_orcamentarias_organizacao_id'))
        batch_op.drop_index(batch_op.f('ix_dotacoes_orcamentarias_exercicio'))

    op.drop_table('dotacoes_orcamentarias')
    # ### end Alembic commands ###
